language: r
warnings_are_errors: true
sudo: false

before_install:
   - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo tlmgr update --self; fi
   - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then sudo tlmgr install framed collection-fontsrecommended; fi

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.4

notifications:
  email: false

r_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
