test_that("triangle", {
    expect_equal(triangle(0, 1, 2)(-5), 0)
    expect_equal(triangle(0, 1, 2)(-1), 0)
    expect_equal(triangle(0, 1, 2)(0), 0)
    expect_equal(triangle(0, 1, 2)(0.5), 0.5)
    expect_equal(triangle(0, 1, 2)(1), 1)
    expect_equal(triangle(0, 1, 2)(1.5), 0.5)
    expect_equal(triangle(0, 1, 2)(2), 0)
    expect_equal(triangle(0, 1, 2)(10), 0)
    expect_equal(triangle(0, 1, 2)(-Inf), 0)
    expect_equal(triangle(0, 1, 2)(Inf), 0)

    expect_equal(triangle(1, 1, 2)(-1), 0)
    expect_equal(triangle(1, 1, 2)(0), 0)
    expect_equal(triangle(1, 1, 2)(1), 1)
    expect_equal(triangle(1, 1, 2)(1.5), 0.5)
    expect_equal(triangle(1, 1, 2)(2), 0)
    expect_equal(triangle(1, 1, 2)(10), 0)
    expect_equal(triangle(1, 1, 2)(-Inf), 0)
    expect_equal(triangle(1, 1, 2)(Inf), 0)

    expect_equal(triangle(0, 1, 1)(-1), 0)
    expect_equal(triangle(0, 1, 1)(0), 0)
    expect_equal(triangle(0, 1, 1)(0.5), 0.5)
    expect_equal(triangle(0, 1, 1)(1), 1)
    expect_equal(triangle(0, 1, 1)(2), 0)
    expect_equal(triangle(0, 1, 1)(10), 0)
    expect_equal(triangle(0, 1, 1)(-Inf), 0)
    expect_equal(triangle(0, 1, 1)(Inf), 0)

    expect_equal(triangle(1, 1, 1)(0), 0)
    expect_equal(triangle(1, 1, 1)(1), 1)
    expect_equal(triangle(1, 1, 1)(2), 0)
    expect_equal(triangle(1, 1, 1)(-Inf), 0)
    expect_equal(triangle(1, 1, 1)(Inf), 0)

    expect_equal(triangle(-Inf, 1, 2)(-5), 1)
    expect_equal(triangle(-Inf, 1, 2)(0), 1)
    expect_equal(triangle(-Inf, 1, 2)(1), 1)
    expect_equal(triangle(-Inf, 1, 2)(1.5), 0.5)
    expect_equal(triangle(-Inf, 1, 2)(2), 0)
    expect_equal(triangle(-Inf, 1, 2)(5), 0)
    expect_equal(triangle(-Inf, 1, 2)(-Inf), 1)
    expect_equal(triangle(-Inf, 1, 2)(Inf), 0)

    expect_equal(triangle(0, 1, Inf)(0), 0)
    expect_equal(triangle(0, 1, Inf)(0.5), 0.5)
    expect_equal(triangle(0, 1, Inf)(1), 1)
    expect_equal(triangle(0, 1, Inf)(2), 1)
    expect_equal(triangle(0, 1, Inf)(5), 1)
    expect_equal(triangle(0, 1, Inf)(-Inf), 0)
    expect_equal(triangle(0, 1, Inf)(Inf), 1)

    expect_equal(triangle(-Inf, 1, Inf)(-5), 1)
    expect_equal(triangle(-Inf, 1, Inf)(0), 1)
    expect_equal(triangle(-Inf, 1, Inf)(1), 1)
    expect_equal(triangle(-Inf, 1, Inf)(2), 1)
    expect_equal(triangle(-Inf, 1, Inf)(5), 1)
    expect_equal(triangle(-Inf, 1, Inf)(-Inf), 1)
    expect_equal(triangle(-Inf, 1, Inf)(Inf), 1)

    expect_equal(triangle(-Inf, -Inf, Inf)(1), 1)
    expect_equal(triangle(-Inf, Inf, Inf)(1), 1)
    expect_equal(triangle(-Inf, Inf, Inf)(-Inf), 1)
    expect_equal(triangle(-Inf, Inf, Inf)(Inf), 1)

    expect_equal(triangle(0, 1, 2)(NA), as.numeric(NA))
    expect_equal(triangle(0, 1, 2)(NaN), as.numeric(NaN))
})


test_that("raisedcos", {
    expect_equal(raisedcos(0, 1, 2)(-5), 0)
    expect_equal(raisedcos(0, 1, 2)(-1), 0)
    expect_equal(raisedcos(0, 1, 2)(0), 0)
    expect_equal(raisedcos(0, 1, 2)(0.5), 0.5)
    expect_equal(raisedcos(0, 1, 2)(1), 1)
    expect_equal(raisedcos(0, 1, 2)(1.5), 0.5)
    expect_equal(raisedcos(0, 1, 2)(2), 0)
    expect_equal(raisedcos(0, 1, 2)(10), 0)
    expect_equal(raisedcos(0, 1, 2)(-Inf), 0)
    expect_equal(raisedcos(0, 1, 2)(Inf), 0)

    expect_equal(raisedcos(1, 1, 2)(-1), 0)
    expect_equal(raisedcos(1, 1, 2)(0), 0)
    expect_equal(raisedcos(1, 1, 2)(1), 1)
    expect_equal(raisedcos(1, 1, 2)(1.5), 0.5)
    expect_equal(raisedcos(1, 1, 2)(2), 0)
    expect_equal(raisedcos(1, 1, 2)(10), 0)
    expect_equal(raisedcos(1, 1, 2)(-Inf), 0)
    expect_equal(raisedcos(1, 1, 2)(Inf), 0)

    expect_equal(raisedcos(0, 1, 1)(-1), 0)
    expect_equal(raisedcos(0, 1, 1)(0), 0)
    expect_equal(raisedcos(0, 1, 1)(0.5), 0.5)
    expect_equal(raisedcos(0, 1, 1)(1), 1)
    expect_equal(raisedcos(0, 1, 1)(2), 0)
    expect_equal(raisedcos(0, 1, 1)(10), 0)
    expect_equal(raisedcos(0, 1, 1)(-Inf), 0)
    expect_equal(raisedcos(0, 1, 1)(Inf), 0)

    expect_equal(raisedcos(1, 1, 1)(0), 0)
    expect_equal(raisedcos(1, 1, 1)(1), 1)
    expect_equal(raisedcos(1, 1, 1)(2), 0)
    expect_equal(raisedcos(1, 1, 1)(-Inf), 0)
    expect_equal(raisedcos(1, 1, 1)(Inf), 0)

    expect_equal(raisedcos(-Inf, 1, 2)(-5), 1)
    expect_equal(raisedcos(-Inf, 1, 2)(0), 1)
    expect_equal(raisedcos(-Inf, 1, 2)(1), 1)
    expect_equal(raisedcos(-Inf, 1, 2)(1.5), 0.5)
    expect_equal(raisedcos(-Inf, 1, 2)(2), 0)
    expect_equal(raisedcos(-Inf, 1, 2)(5), 0)
    expect_equal(raisedcos(-Inf, 1, 2)(-Inf), 1)
    expect_equal(raisedcos(-Inf, 1, 2)(Inf), 0)

    expect_equal(raisedcos(0, 1, Inf)(0), 0)
    expect_equal(raisedcos(0, 1, Inf)(0.5), 0.5)
    expect_equal(raisedcos(0, 1, Inf)(1), 1)
    expect_equal(raisedcos(0, 1, Inf)(2), 1)
    expect_equal(raisedcos(0, 1, Inf)(5), 1)
    expect_equal(raisedcos(0, 1, Inf)(-Inf), 0)
    expect_equal(raisedcos(0, 1, Inf)(Inf), 1)

    expect_equal(raisedcos(-Inf, 1, Inf)(-5), 1)
    expect_equal(raisedcos(-Inf, 1, Inf)(0), 1)
    expect_equal(raisedcos(-Inf, 1, Inf)(1), 1)
    expect_equal(raisedcos(-Inf, 1, Inf)(2), 1)
    expect_equal(raisedcos(-Inf, 1, Inf)(5), 1)
    expect_equal(raisedcos(-Inf, 1, Inf)(Inf), 1)
    expect_equal(raisedcos(-Inf, 1, Inf)(-Inf), 1)

    expect_equal(raisedcos(-Inf, -Inf, Inf)(1), 1)
    expect_equal(raisedcos(-Inf, Inf, Inf)(1), 1)
    expect_equal(raisedcos(-Inf, Inf, Inf)(Inf), 1)
    expect_equal(raisedcos(-Inf, Inf, Inf)(-Inf), 1)

    expect_equal(raisedcos(0, 1, 2)(NA), as.numeric(NA))
    expect_equal(raisedcos(0, 1, 2)(NaN), as.numeric(NaN))
})
