# Generated by rmake: do not edit by hand
SHELL=/bin/sh
R="$(R_HOME)/bin$(R_ARCH)/Rscript"
RM=rm
CP=cp

.PHONY: all
all: Makefile rcode.tex exportChunks.log
	
rcode.tex: rcode.Rtex
	$(R) -e '{' \
	-e '    library(knitr)' \
	-e '    params <- list(.target = "rcode.tex", .script = "rcode.Rtex", .depends = "rcode.Rtex", .task = "all")' \
	-e '    knitr::knit("rcode.Rtex", output = "rcode.tex")' \
	-e '}'
exportChunks.log: exportChunks.R rcode.tex
	$(R) -e '{' \
	-e '    params <- list(.target = "exportChunks.log", .script = "exportChunks.R", .depends = "rcode.tex", .task = "all")' \
	-e '    source("exportChunks.R")' \
	-e '}'
.PHONY: clean
clean: 
	$(RM) rcode.tex
	$(RM) exportChunks.log
Makefile: Makefile.R
	$(R) -e '{' \
	-e '    params <- list(.target = "Makefile", .script = "Makefile.R", .depends = NULL, .task = "all")' \
	-e '    source("Makefile.R")' \
	-e '}'
